CREATE OR REPLACE VIEW v_flat_citation AS
SELECT
    ci.citation_nbr,
    substr(ci.citation_nbr, 1, 3) || 'XXXX' AS citation_nbr_trunc,
    ci.check_digit,
    ci.key_date AS key_citation_dt,
    dd.crash_yr AS citation_yr,
    dd.crash_mm AS citation_mm,
    dd.crash_mo AS citation_mo,
    dd.crash_dd AS citation_dd,
    dd.crash_day AS citation_day,
    ci.key_geography,
    dg.dot_district_nm,
    dg.rpc_nm,
    dg.mpo_nm,
    dg.cnty_cd,
    dg.cnty_nm,
    dg.city_cd,
    dg.city_nm,
    ci.key_agncy,
    da.agncy_nm,
    da.agncy_short_nm,
    da.agncy_type_nm,
    ci.key_driver_age_rng,
    vdar.driver_attr_tx AS driver_age_rng,
    ci.key_violation,
    nvl(vi.sect_nbr, ci.sect_nbr) AS sect_nbr,
    nvl(vi.sect_nbr_dsp, ci.sect_nbr) AS sect_nbr_dsp,
    nvl(vi.sub_sect_nbr, ci.sub_sect_nbr) AS sub_sect_nbr,
    nvl(vi.sub_sect_nbr_dsp, ci.sub_sect_nbr) AS sub_sect_nbr_dsp,
    nvl(vi.violation_cd, ci.violation_cd) AS violation_cd,
    vi.violation_desc,
    vi.violation_class,
    vi.violation_type,
    ci.offense_dt,
    ci.driver_addr_diff_than_dl,
    ci.driver_addr_city_nm,
    ci.driver_addr_state_cd,
    ci.driver_addr_zip_cd,
    ci.driver_age_nbr,
    ci.driver_race_cd,
    ci.driver_gender_cd,
    ci.driver_height_tx,
    ci.dl_state_cd,
    ci.dl_class_cd,
    ci.dl_expir_yr,
    ci.comm_veh_cd,
    ci.veh_yr,
    ci.veh_make_tx,
    ci.veh_style_tx,
    ci.veh_color_tx,
    ci.hazmat_cd,
    ci.veh_state_cd,
    ci.veh_tag_expir_yr,
    ci.companion_citation_cd,
    ci.violation_loc_tx,
    ci.offset_feet_meas,
    ci.offset_miles_meas,
    ci.offset_dir_cd,
    ci.offset_from_node_id,
    ci.actual_speed_meas,
    ci.posted_speed_meas,
    ci.hwy_4lane_cd,
    ci.hwy_intrstate_cd,
    ci.violation_careless_cd,
    ci.violation_device_cd,
    ci.violation_row_cd,
    ci.violation_lane_cd,
    ci.violation_passing_cd,
    ci.violation_child_restraint_cd,
    ci.violation_dui_cd,
    ci.driver_bal_meas,
    ci.violation_seatbelt_cd,
    ci.violation_equip_cd,
    ci.violation_tag_less_cd,
    ci.violation_tag_more_cd,
    ci.violation_ins_cd,
    ci.violation_expir_dl_cd,
    ci.violation_expir_dl_more_cd,
    ci.violation_no_valid_dl_cd,
    ci.violation_susp_dl_cd,
    ci.oth_comments_tx,
    ci.fl_dl_edit_override_cd,
    ci.state_statute_cd,
    ci.crash_cd,
    ci.prop_dmg_cd,
    ci.prop_dmg_amt,
    ci.inj_cd,
    ci.serious_inj_cd,
    ci.fatal_inj_cd,
    ci.method_of_arrest_cd,
    ci.criminal_appear_reqd_cd,
    ci.infraction_appear_reqd_cd,
    ci.infraction_no_appear_reqd_cd,
    ci.court_dt,
    ci.court_nm,
    ci.court_addr_tx,
    ci.court_city_nm,
    ci.court_state_cd,
    ci.court_zip_cd,
    ci.arrest_delivered_to_tx,
    ci.arrest_delivered_dt,
    ci.ofcr_rank_tx,
    ci.trooper_unit_tx,
    ci.bal_008_or_above_cd,
    ci.dui_refuse_cd,
    ci.dui_lic_surrendered_cd,
    ci.dui_lic_rsn_tx,
    ci.dui_eligible_cd,
    ci.dui_eligible_rsn_tx,
    ci.dui_bar_ofc_tx,
    ci.status_cd,
    ci.aggressive_driver_cd,
    ci.criminal_cd,
    ci.fine_amt,
    ci.issue_arrest_dt,
    ci.ofcr_dlvry_verif_cd,
    ci.due_dt,
    ci.motorcycle_cd,
    ci.veh_16_pass_cd,
    ci.ofcr_re_exam_cd,
    ci.dui_pass_under_18_cd,
    ci.e_citation_cd,
    ci.nm_chg_cd,
    ci.comm_dl_cd,
    ci.violation_sig_red_light_cd,
    ci.violation_workers_present_cd,
    ci.violation_handheld_cd,
    ci.violation_sch_zn_cd,
    ci.perm_reg_cd,
    ci.compliance_dt,
    ci.speed_meas_device_id,
    ci.dl_seize_cd,
    ci.business_cd,
    ci.source_format_cd,
    ci.addr_used_cd,
    CASE
        WHEN ci.gps_lng IS NULL OR ci.gps_lat IS NULL THEN NULL
        ELSE sdo_geometry(2001, 4326, mdsys.sdo_point_type(ci.gps_lng, ci.gps_lat, NULL), NULL, NULL)
    END AS gps_pt_4326,
    CASE
        WHEN sc.shape IS NULL THEN NULL
        ELSE sdo_geometry(sde.st_astext(sc.shape), 3087)
    END AS geocode_pt_3087,
    ci.last_updt_dt
FROM citation ci
LEFT JOIN navteq_2015q1.st_citation sc ON sc.citation_nbr = ci.citation_nbr
LEFT JOIN dim_date dd ON dd.crash_dt = ci.key_date
LEFT JOIN dim_violation vi ON vi.id = ci.key_violation
LEFT JOIN dim_agncy da ON ci.key_agncy = da.id
LEFT JOIN dim_geography dg ON ci.key_geography = dg.id
LEFT JOIN v_driver_age_rng vdar ON vdar.id = ci.key_driver_age_rng
;
