CREATE OR REPLACE VIEW v_geocode_result_for_sdo
AS SELECT
  objectid,
  hsmv_rpt_nbr,
  score_nbr,
  location_type_cd,
  match_status_cd,
  match_result_cd,
  std_addr_tx,
  match_addr_tx,
  addr_used_cd,
  city_used_cd,
  bypass_used_cd,
  custom_geocoder_used_cd,
  unmatched_desc_cd,
  map_point_x,
  map_point_y,
  map_point_srid,
  center_line_x,
  center_line_y,
  center_line_srid,
  crash_seg_id,
  nearest_intrsect_id,
  nearest_intrsect_offset_ft,
  nearest_intrsect_offset_dir,
  ref_intrsect_id,
  ref_intrsect_offset_ft,
  ref_intrsect_offset_dir,
  updt_dir_travel,
  last_updt_user_id,
  last_updt_dt,
  sym_angle,
  source_format_cd,
  geocode_engine_cd,
  method_used_cd,
  on_network,
  dot_on_sys,
  key_geography,
  city_cd,
  cnty_cd,
  mapped,
  batch_nbr,
  CASE WHEN shape IS NULL THEN NULL ELSE sdo_geometry(sde.st_astext(shape), 3087) END AS shape,
  author,
  st_nm,
  intrsect_st_nm,
  st_nbr,
  fail_match_rsn_cd,
  re_geolocated_from_ver,
  am_intrsect_id,
  am_intrsect_offset_ft,
  am_intrsect_offset_dir,
  rel_to_network
FROM geocode_result;

CREATE OR REPLACE VIEW v_st_citation_for_sdo
AS SELECT
  objectid,
  citation_nbr,
  CASE WHEN shape IS NULL THEN NULL ELSE sdo_geometry(sde.st_astext(shape), 3087) END AS shape,
  mpo_bnd_id
FROM st_citation;
