CREATE OR REPLACE PROCEDURE s4_sync_pass (p_days_back INT DEFAULT NULL)
AS
    v_start_dt DATE;
BEGIN
    v_start_dt := CASE WHEN p_days_back IS NOT NULL THEN TRUNC(SYSDATE - p_days_back) ELSE NULL END;

    IF v_start_dt IS NULL THEN
        EXECUTE IMMEDIATE 'TRUNCATE TABLE pass';
    ELSE
        DELETE FROM pass ps
        WHERE EXISTS (
            SELECT 1
            FROM v_flat_pass@s4_warehouse vp
            WHERE vp.last_updt_dt >= v_start_dt
            AND vp.hsmv_rpt_nbr = ps.hsmv_rpt_nbr
        );
    END IF;

    INSERT INTO pass (
        hsmv_rpt_nbr,
        hsmv_rpt_nbr_trunc,
        veh_nbr,
        person_nbr,
        key_crash_dt,
        crash_yr,
        crash_mm,
        crash_mo,
        crash_dd,
        crash_day,
        key_geography,
        dot_district_nm,
        rpc_nm,
        mpo_nm,
        cnty_cd,
        cnty_nm,
        city_cd,
        city_nm,
        key_rptg_agncy,
        rptg_agncy_nm,
        rptg_agncy_short_nm,
        rptg_agncy_type,
        key_rptg_unit,
        rptg_unit_nm,
        rptg_unit_short_nm,
        key_age_rng,
        age_rng,
        key_airbag_deployed,
        airbag_deployed,
        key_ejection,
        ejection,
        key_gender,
        gender,
        key_helmet_use,
        helmet_use,
        key_inj_sev,
        inj_sev,
        key_restraint_sys,
        restraint_sys,
        key_seating_other,
        seating_other,
        key_seating_row,
        seating_row,
        key_seating_seat,
        seating_seat,
        key_src_of_trans,
        src_of_trans,
        key_veh_body_type,
        veh_body_type,
        addr_city,
        addr_state,
        addr_zip,
        dl_state,
        is_using_eye_protection,
        fatality_cnt,
        fatality_unrestrained_cnt,
        inj_cnt,
        inj_unrestrained_cnt,
        citation_cnt,
        citation_amt,
        prop_dmg_cnt,
        batch_nbr,
        inj_incapacitating_cnt,
        prop_dmg_amt
    )
    SELECT
        hsmv_rpt_nbr,
        hsmv_rpt_nbr_trunc,
        veh_nbr,
        person_nbr,
        key_crash_dt,
        crash_yr,
        crash_mm,
        crash_mo,
        crash_dd,
        crash_day,
        key_geography,
        dot_district_nm,
        rpc_nm,
        mpo_nm,
        cnty_cd,
        cnty_nm,
        city_cd,
        city_nm,
        key_rptg_agncy,
        rptg_agncy_nm,
        rptg_agncy_short_nm,
        rptg_agncy_type,
        key_rptg_unit,
        rptg_unit_nm,
        rptg_unit_short_nm,
        key_age_rng,
        age_rng,
        key_airbag_deployed,
        airbag_deployed,
        key_ejection,
        ejection,
        key_gender,
        gender,
        key_helmet_use,
        helmet_use,
        key_inj_sev,
        inj_sev,
        key_restraint_sys,
        restraint_sys,
        key_seating_other,
        seating_other,
        key_seating_row,
        seating_row,
        key_seating_seat,
        seating_seat,
        key_src_of_trans,
        src_of_trans,
        key_veh_body_type,
        veh_body_type,
        addr_city,
        addr_state,
        addr_zip,
        dl_state,
        is_using_eye_protection,
        fatality_cnt,
        fatality_unrestrained_cnt,
        inj_cnt,
        inj_unrestrained_cnt,
        citation_cnt,
        citation_amt,
        prop_dmg_cnt,
        batch_nbr,
        inj_incapacitating_cnt,
        prop_dmg_amt
    FROM v_flat_pass@s4_warehouse vp
    WHERE v_start_dt IS NULL
    OR vp.last_updt_dt >= v_start_dt;

    -- veh

    IF v_start_dt IS NULL THEN
        DELETE FROM veh;
    ELSE
        DELETE FROM veh
        WHERE EXISTS (
            SELECT 1
            FROM v_flat_veh@s4_warehouse vv
            WHERE vv.last_updt_dt >= v_start_dt
            AND vv.hsmv_rpt_nbr = veh.hsmv_rpt_nbr
        );
    END IF;

    INSERT INTO veh (
        hsmv_rpt_nbr,
        hsmv_rpt_nbr_trunc,
        veh_nbr,
        key_crash_dt,
        crash_yr,
        crash_mm,
        crash_mo,
        crash_dd,
        crash_day,
        key_geography,
        dot_district_nm,
        rpc_nm,
        mpo_nm,
        cnty_cd,
        cnty_nm,
        city_cd,
        city_nm,
        key_rptg_agncy,
        rptg_agncy_nm,
        rptg_agncy_short_nm,
        rptg_agncy_type,
        key_rptg_unit,
        rptg_unit_nm,
        rptg_unit_short_nm,
        key_ar_of_init_impact,
        ar_of_init_impact,
        key_body_type,
        body_type,
        key_cargo_body_type,
        cargo_body_type,
        key_cmv_config,
        cmv_config,
        key_comm_non_comm,
        comm_non_comm,
        key_dmg_extent,
        dmg_extent,
        key_dir_before,
        dir_before,
        key_gvwr_gcwr,
        gvwr_gcwr,
        key_he1,
        he1,
        key_he2,
        he2,
        key_he3,
        he3,
        key_he4,
        he4,
        key_maneuver_action,
        maneuver_action,
        key_most_dmg_ar,
        most_dmg_ar,
        key_most_he,
        most_he,
        key_rd_align,
        rd_align,
        key_rd_grade,
        rd_grade,
        key_special_func,
        special_func,
        key_traffic_ctl,
        traffic_ctl,
        key_trafficway,
        trafficway,
        key_veh_defect1,
        veh_defect1,
        key_veh_defect2,
        veh_defect2,
        key_veh_type,
        veh_type,
        key_wrecker_sel,
        wrecker_sel,
        est_speed,
        is_comm_veh,
        is_emerg_veh,
        is_hazmat_released,
        is_hit_and_run,
        is_owner_a_business,
        is_perm_reg,
        is_towed_due_to_dmg,
        motor_carrier_city,
        motor_carrier_state,
        motor_carrier_zip,
        placard_hazmat_class,
        posted_speed,
        reg_state,
        tot_lanes,
        traveling_on_st,
        veh_color,
        veh_make,
        veh_model,
        veh_owner_city,
        veh_owner_state,
        veh_owner_zip,
        veh_style,
        veh_yr,
        moped_cnt,
        motorcycle_cnt,
        pass_cnt,
        trailer_cnt,
        fatality_cnt,
        fatality_unrestrained_cnt,
        inj_cnt,
        inj_unrestrained_cnt,
        citation_cnt,
        citation_amt,
        prop_dmg_cnt,
        prop_dmg_amt,
        veh_dmg_cnt,
        veh_dmg_amt,
        tot_dmg_amt,
        inj_incapacitating_cnt,
        batch_nbr,
        inj_none_cnt,
        inj_possible_cnt,
        inj_non_incapacitating_cnt,
        inj_fatal_30_cnt,
        inj_fatal_non_traffic_cnt
    )
    SELECT
        hsmv_rpt_nbr,
        hsmv_rpt_nbr_trunc,
        veh_nbr,
        key_crash_dt,
        crash_yr,
        crash_mm,
        crash_mo,
        crash_dd,
        crash_day,
        key_geography,
        dot_district_nm,
        rpc_nm,
        mpo_nm,
        cnty_cd,
        cnty_nm,
        city_cd,
        city_nm,
        key_rptg_agncy,
        rptg_agncy_nm,
        rptg_agncy_short_nm,
        rptg_agncy_type,
        key_rptg_unit,
        rptg_unit_nm,
        rptg_unit_short_nm,
        key_ar_of_init_impact,
        ar_of_init_impact,
        key_body_type,
        body_type,
        key_cargo_body_type,
        cargo_body_type,
        key_cmv_config,
        cmv_config,
        key_comm_non_comm,
        comm_non_comm,
        key_dmg_extent,
        dmg_extent,
        key_dir_before,
        dir_before,
        key_gvwr_gcwr,
        gvwr_gcwr,
        key_he1,
        he1,
        key_he2,
        he2,
        key_he3,
        he3,
        key_he4,
        he4,
        key_maneuver_action,
        maneuver_action,
        key_most_dmg_ar,
        most_dmg_ar,
        key_most_he,
        most_he,
        key_rd_align,
        rd_align,
        key_rd_grade,
        rd_grade,
        key_special_func,
        special_func,
        key_traffic_ctl,
        traffic_ctl,
        key_trafficway,
        trafficway,
        key_veh_defect1,
        veh_defect1,
        key_veh_defect2,
        veh_defect2,
        key_veh_type,
        veh_type,
        key_wrecker_sel,
        wrecker_sel,
        est_speed,
        is_comm_veh,
        is_emerg_veh,
        is_hazmat_released,
        is_hit_and_run,
        is_owner_a_business,
        is_perm_reg,
        is_towed_due_to_dmg,
        motor_carrier_city,
        motor_carrier_state,
        motor_carrier_zip,
        placard_hazmat_class,
        posted_speed,
        reg_state,
        tot_lanes,
        traveling_on_st,
        veh_color,
        veh_make,
        veh_model,
        veh_owner_city,
        veh_owner_state,
        veh_owner_zip,
        veh_style,
        veh_yr,
        moped_cnt,
        motorcycle_cnt,
        pass_cnt,
        trailer_cnt,
        fatality_cnt,
        fatality_unrestrained_cnt,
        inj_cnt,
        inj_unrestrained_cnt,
        citation_cnt,
        citation_amt,
        prop_dmg_cnt,
        prop_dmg_amt,
        veh_dmg_cnt,
        veh_dmg_amt,
        tot_dmg_amt,
        inj_incapacitating_cnt,
        batch_nbr,
        inj_none_cnt,
        inj_possible_cnt,
        inj_non_incapacitating_cnt,
        inj_fatal_30_cnt,
        inj_fatal_non_traffic_cnt
    FROM v_flat_veh@s4_warehouse vv
    WHERE v_start_dt IS NULL
    OR vv.last_updt_dt >= v_start_dt;

    -- violation

    IF v_start_dt IS NULL THEN
        DELETE FROM violation;
    ELSE
        DELETE FROM violation vi
        WHERE EXISTS (
            SELECT 1
            FROM v_flat_violation@s4_warehouse vv
            WHERE vv.last_updt_dt >= v_start_dt
            AND vv.hsmv_rpt_nbr = vi.hsmv_rpt_nbr
        );
    END IF;

    INSERT INTO violation (
        hsmv_rpt_nbr,
        hsmv_rpt_nbr_trunc,
        person_nbr,
        citation_nbr,
        citation_nbr_trunc,
        key_crash_dt,
        crash_yr,
        crash_mm,
        crash_mo,
        crash_dd,
        crash_day,
        key_geography,
        dot_district_nm,
        rpc_nm,
        mpo_nm,
        cnty_cd,
        cnty_nm,
        city_cd,
        city_nm,
        key_rptg_agncy,
        rptg_agncy_nm,
        rptg_agncy_short_nm,
        rptg_agncy_type,
        key_rptg_unit,
        rptg_unit_nm,
        rptg_unit_short_nm,
        fl_statute_nbr,
        charge,
        batch_nbr
    )
    SELECT
        hsmv_rpt_nbr,
        hsmv_rpt_nbr_trunc,
        person_nbr,
        citation_nbr,
        citation_nbr_trunc,
        key_crash_dt,
        crash_yr,
        crash_mm,
        crash_mo,
        crash_dd,
        crash_day,
        key_geography,
        dot_district_nm,
        rpc_nm,
        mpo_nm,
        cnty_cd,
        cnty_nm,
        city_cd,
        city_nm,
        key_rptg_agncy,
        rptg_agncy_nm,
        rptg_agncy_short_nm,
        rptg_agncy_type,
        key_rptg_unit,
        rptg_unit_nm,
        rptg_unit_short_nm,
        fl_statute_nbr,
        charge,
        batch_nbr
    FROM v_flat_violation@s4_warehouse vv
    WHERE v_start_dt IS NULL
    OR vv.last_updt_dt >= v_start_dt;

    COMMIT;
END;
/
