/*
EXECUTE AS SYSDBA ON CONTAINER DATABASE
*/

ALTER PLUGGABLE DATABASE ORCLPDB CLOSE;
ALTER PLUGGABLE DATABASE ORCLPDB OPEN READ WRITE;
ALTER PLUGGABLE DATABASE ORCLPDB SAVE STATE;

/*
EXECUTE AS SYSDBA ON PLUGGABLE DATABASE
*/

-- USER SQL
CREATE USER s4_warehouse_ng IDENTIFIED BY crash418b
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "CTXAPP" TO s4_warehouse_ng ;
GRANT "CONNECT" TO s4_warehouse_ng ;
GRANT "RESOURCE" TO s4_warehouse_ng ;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO s4_warehouse_ng ;
GRANT DEBUG CONNECT SESSION TO s4_warehouse_ng ;
GRANT CREATE MATERIALIZED VIEW TO s4_warehouse_ng ;
GRANT CREATE ANY INDEX TO s4_warehouse_ng ;
GRANT DEBUG ANY PROCEDURE TO s4_warehouse_ng ;
GRANT CREATE VIEW TO s4_warehouse_ng ;
GRANT CREATE TABLE TO s4_warehouse_ng ;
GRANT CREATE DATABASE LINK TO s4_warehouse_ng ;
GRANT UNLIMITED TABLESPACE TO s4_warehouse_ng ;
