/*
EXECUTE AS SYSDBA
*/

-- USER SQL
CREATE USER s4_warehouse IDENTIFIED BY crash418b
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "CTXAPP" TO s4_warehouse ;
GRANT "CONNECT" TO s4_warehouse ;
GRANT "RESOURCE" TO s4_warehouse ;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO s4_warehouse ;
GRANT DEBUG CONNECT SESSION TO s4_warehouse ;
GRANT CREATE MATERIALIZED VIEW TO s4_warehouse ;
GRANT CREATE ANY INDEX TO s4_warehouse ;
GRANT DEBUG ANY PROCEDURE TO s4_warehouse ;
GRANT CREATE VIEW TO s4_warehouse ;
GRANT CREATE TABLE TO s4_warehouse ;
GRANT CREATE DATABASE LINK TO s4_warehouse ;
GRANT UNLIMITED TABLESPACE TO s4_warehouse ;
